+incdir+../../rtl/common
+incdir+../uvm/if
+incdir+../uvm/env
+incdir+../uvm/test
+incdir+../uvm/common
+
+../../rtl/common/sf_defs.svh
+../../rtl/common/sf_rst_sync.sv
+../../rtl/common/sf_cdc_sync.sv
+
+../../rtl/bus/apb_decoder.sv
+../../rtl/top/sf_soc_pkg.sv
+
+../../rtl/ip/pmu/sf_pmu_pkg.sv
+../../rtl/ip/pmu/sf_pmu_reg_top.sv
+../../rtl/ip/pmu/sf_pmu_core.sv
+../../rtl/ip/pmu/sf_pmu_top.sv
+
+../../rtl/ip/rtc/sf_rtc_pkg.sv
+../../rtl/ip/rtc/sf_rtc_reg_top.sv
+../../rtl/ip/rtc/sf_rtc_core.sv
+../../rtl/ip/rtc/sf_rtc_top.sv
+
+../../rtl/ip/gpio/sf_gpio_pkg.sv
+../../rtl/ip/gpio/sf_gpio_reg_top.sv
+../../rtl/ip/gpio/sf_gpio_core.sv
+../../rtl/ip/gpio/sf_gpio_top.sv
+
+../../rtl/ip/timer_wdt/sf_timer_wdt_pkg.sv
+../../rtl/ip/timer_wdt/sf_timer_wdt_reg_top.sv
+../../rtl/ip/timer_wdt/sf_timer_wdt_core.sv
+../../rtl/ip/timer_wdt/sf_timer_wdt_top.sv
+
+../../rtl/ip/uart/sf_uart_pkg.sv
+../../rtl/ip/uart/sf_uart_reg_top.sv
+../../rtl/ip/uart/sf_uart_core.sv
+../../rtl/ip/uart/sf_uart_top.sv
+
+../../rtl/ip/spi/sf_spi_pkg.sv
+../../rtl/ip/spi/sf_spi_reg_top.sv
+../../rtl/ip/spi/sf_spi_core.sv
+../../rtl/ip/spi/sf_spi_top.sv
+
+../../rtl/ip/i2c/sf_i2c_pkg.sv
+../../rtl/ip/i2c/sf_i2c_reg_top.sv
+../../rtl/ip/i2c/sf_i2c_core.sv
+../../rtl/ip/i2c/sf_i2c_top.sv
+
+../../rtl/ip/udma/sf_udma_pkg.sv
+../../rtl/ip/udma/sf_udma_reg_top.sv
+../../rtl/ip/udma/sf_udma_core.sv
+../../rtl/ip/udma/sf_udma_top.sv
+
+../../rtl/ip/event_intc/sf_event_intc_pkg.sv
+../../rtl/ip/event_intc/sf_event_intc_reg_top.sv
+../../rtl/ip/event_intc/sf_event_intc_core.sv
+../../rtl/ip/event_intc/sf_event_intc_top.sv
+
+../../rtl/ip/fusion/sf_fusion_pkg.sv
+../../rtl/ip/fusion/sf_fusion_reg_top.sv
+../../rtl/ip/fusion/sf_fusion_core.sv
+../../rtl/ip/fusion/sf_fusion_top.sv
+
+../../rtl/top/sf_soc_top.sv
+
+../uvm/if/apb_if.sv
+../uvm/common/soc_uvm_pkg.sv
+../uvm/tb/tb_top.sv
